#!/usr/bin/python2.7

from livereload.task import Task
from livereload.compiler import lessc

Task.add('js/main.js')
Task.add('js/plugins.js')
Task.add('js/private-cloud.js')
Task.add('*.html')
# Recompile less on change -- requires lessc dlobally (npm install less -g)
Task.add('css/main.less', lessc('css/main.less', 'css/main.css'))
