#!/usr/bin/python2.7

from livereload.task import Task
from livereload.compiler import lessc

Task.add('js/main.js')
Task.add('js/plugins.js')
Task.add('js/private-cloud.js')
Task.add('*.html')
Task.add('templates/*.html')

# Recompile less on change -- requires lessc globally (npm install less -g)
Task.add('css/variables.less', lessc('css/main.less', 'css/main.css'))
Task.add('css/variables.less', lessc('css/navbar.less', 'css/navbar.css'))
Task.add('css/main.less', lessc('css/main.less', 'css/main.css'))
Task.add('css/navbar.less', lessc('css/navbar.less', 'css/navbar.css'))